### ISSUE TITLE
Command for rewinding core_resource setup script version numbers

### ISSUE THREAD

**Issue by kalenjordan** [netz98/n98-magerun#133]
One thing that I find myself doing frequently when testing upgrade scripts is manually going into core_resource and bumping version numbers down, for example if my upgrade script doesn't work the first time around and I have to retest it.

I was thinking sys:setup:rewind could be useful for this - bump the core_resource version number down by one point increment and clear cache.

Let me know if that sounds useful and I'll contribute it.

**Comment by robbieaverill** [comment]
Would this not be covered now by `sys:setup:change-version`?

**Comment by ktomk** [comment]
Yes, it's possible to use `sys:setup:change-version` to rewind a modules version nowadays.

IIRC Magicento rewinds it to the previous one without specifically naming the version (and module as it detects it from context). It can do so because the setup script has both, the from-version and the to-version.

So for the main feature request: It's already implemented.

For more details, Magerun would need to parse the setup script revisions of a module. It's technically possible (parsing the versions from the latest setup script) but I don't know if it's worth the work. When I rewound with Magerun, I did so to a specific number and was typed in once, rest was replaying the command from history in bash.

I close this for now, if you have strong objections, please let me know @robbieaverill.
