### ISSUE TITLE
install command with --no-interaction still requires user input

### ISSUE THREAD

**Issue by Vinai** [netz98/n98-magerun#256]
When running the command

```
install --magentoVersion=1 --installationFolder=/var/www/magento/htdocs --dbHost=localhost --dbUser=root --dbPass=password123 --dbName=magento --installSampleData=yes --baseUrl=http://magento.dev/ --replaceHtaccessFile=no --useDefaultConfigParams=yes --no-ansi --no-interaction
```

I still am prompted:

```
Write BaseURL to .htaccess file? [n]:
```

n98-magerun version is 1.82.0

**Comment by pocallaghan** [comment]
As of Symfony Console v2.4 the `DialogHelper::ask` method has returned the default value if `--no-interaction` is in use. I believe this means this particular issue no longer exists. It also largely mitigates the requirement to do a mass refactor and move question into the `interact` method. The `DialogHelper` has been deprecated in favour of the `QuestionHelper`, but that's another issue. This issue can potentially be considered closed.

**Comment by tkn98** [comment]
Sometimes we even have eternal loops asking for input but then not asking and taking the default to validation which fails then asking again but not asking and taking the default to validation ... .. .

Each command that needs actual support for this base feature needs to be patched. I suggest to concentrate on concrete requirements then. For the install command it's possible to provide all values upfront so a potential candidate. But no traction since a long time, so I will close. I'm happy with re-opening if this becomes a concrete requirement again.
