### ISSUE TITLE
Magento CE Installation 1.9.0.1 not working

### ISSUE THREAD

**Issue by npostulart** [netz98/n98-magerun#365]
When I try to install the current 1.9.0.1 Version of Magento CE the installation seems to work but I only get a `_n98_magerun_download` folder with a single `.gz` file inside.

I already cleared the composer cache without any changes. Installation of 1.8.1.0 works fine. The cache files in composer are in the same format (`.tar`) and the `1.9.0.1-.tar` files is not damaged. We are working on OSX 10.9 with the latest versions of `composer` and `magerun`.

Any hints what to do?

**Comment by TommyKolkman** [comment]
Thanks AydinHassan, this fixed it for me. 

However, I now have the problem that the installation process is still incorrect. The language isn't created for me, the admin user as well (so I can't login). Any idea? Running PHP 5.6.2 via MAMP here. I've installed without sample data to be sure.

Any idea?

**Comment by cmuench** [comment]
Should Magento 1.9.0.1 running with PHP 5.6.x without any core modification? Magento officially supports only PHP 5.5.

**Comment by TommyKolkman** [comment]
Christian, thanks for the quick reply. With 5.5 it all seems to work, the only thing however, is that the admin language file doesn't seem to be installed to correctly. Might be a MAMP setting somewhere that overwrites a locale whatsoever, but I'm not sure.

**Comment by diazwatson** [comment]
Increasing my "memory_limit" from 128M to 512M worked for me!

**Comment by tkn98** [comment]
We perhaps could register some fatal error handler with magerun. Then these kind of fatals wouldn't got unnoticed. (I heard this one implements such by registering as shutdown handler https://github.com/Seldaek/monolog/blob/master/src/Monolog/ErrorHandler.php)

**Comment by ktomk** [comment]
Could now reproduce on one machine. It had the 128M default for memory_limit. Goes through with 512M, 256M was sufficient as well.

A workaround is to override the ini-setting of memory_limit on the commandline. Consider your path to n98-magerun.phar:

    $ php -dmemory_limit=512M -f /path/to/n98-magerung.phar -- install

(I recommend 512M with 256M it was a bit slow here, but it worked at least for the installer. It crashed with 256M for the sample data download at ~35%)

This is a workaround, but it works with the current version already.

**But** 256M was not enough for the sample data. So this is another component to take into account when looking for a well suited minimum memory_limit.

The error is more or less a configuration issue. But for convenient usage the magerun install command should deal with it in advance instead of a hard and unfriendly fail.

To fix this, I think per version there should be a minimum required amount of memory configured. magerun should check if the current php ini `memory_limit` setting is below it (that minimum memory_limit reuired). this check/operation needs some routine to deal with the shorthand notation but solid ones should be copy&paste available. In case the memory_limit configured is too low (e.g. the default 128M) raise it to the (recommended) minimum (e.g. 512M). the user should be informed that the memory limit has been raised and from which value to which value. the raise-operation has to be verified as well. in case it was not successful, and error should be given and the installation command should be rejected as requirements were not met.

I dunno if it makes further sense to find out why 1.9.0.1 needs more memory. I assume it's the size of the .gz file so it could make sense to gather information in the future if the memory needs are predictable so it's not a patching after but knowing upfront.

But most likely the issue is that users haven't the CLI php.ini config set well for magerun/magento. Most systems that have magento running should allow to raise the memory_limit to 512M. Alternatively it could be considerable to - if setting to 512M fails - 256M is used. It will crash with sample data then.

**Comment by tkn98** [comment]
Since fc84c8a9dfae666fd5ec4da4ce85f7050f0ee45b these errors are not hidden any longer.

General PHP settings requirements are tracked in #707.

No traction since longer also signal that current version is not so prone to this error any longer.
