### ISSUE TITLE
Bash auto completion not working

### ISSUE THREAD

**Issue by conveydk** [netz98/n98-magerun#481]
I've installed [the bash auto completion script](https://github.com/netz98/n98-magerun#bash). But when I ex. try to run: 

`n98-magerun.phar` <kbd>TAB</kbd> <kbd>TAB</kbd>

I get this:

    magerun usage: paste [-s] [-d delimiters] file ...
    -bash: __ltrim_colon_completions: command not found

**Comment by tkn98** [comment]
Please open your shell and enter the following command:

    $ __ltrim_colon_completions

And then report back your output. Next to that also please enter the following command:

    $ uname -a && __ltrim_colon_completions

And then report back your output.

Additionally please describe which operating system and which version your using.

**Comment by conveydk** [comment]
```
$ type __ltrim_colon_completions
-bash: type: __ltrim_colon_completions: command not found
$ uname -a && __ltrim_colon_completions
Darwin macbook-pro-2.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
-bash: __ltrim_colon_completions: command not found
```
Mac OS X 10.10.1

**Comment by tkn98** [comment]
Looks like that on your Mac OS X you don't have the function `__ltrim_colon_completions` as part of your bash. Please compare with my output:

	$ type __ltrim_colon_completions
	__ltrim_colon_completions is a function
	__ltrim_colon_completions () 
	{ 
		if [[ "$1" == *:* && "$COMP_WORDBREAKS" == *:* ]]; then
			local colon_word=${1%"${1##*:}"};
			local i=${#COMPREPLY[*]};
			while [[ $((--i)) -ge 0 ]]; do
				COMPREPLY[$i]=${COMPREPLY[$i]#"$colon_word"};
			done;
		fi
	}

AFAIK this bash function is used for multiple autocompletions (different packages) on linux.

It's perhaps a problem that other Mac OSX users (independent to n98-magerun) have already solved in the past. I'm not a Mac OSX user so that I can't quickly google and try things.

**Comment by conveydk** [comment]
Thanks for your help! This gives me something to look further into.

**Comment by tkn98** [comment]
You're welcome. If you find out more, please report back to this issue here on Github to have this a little more documented.

**Comment by conveydk** [comment]
Which version of bash are you running?

**Comment by tkn98** [comment]
> My Bash: GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by conveydk** [comment]
No I've got the `__ltrim_colon_completions` to work. But I'm getting the following:

```
n98-magerun.phar usage: paste [-s] [-d delimiters] file ...
```

**Comment by tkn98** [comment]
I installed it with `$ https://github.com/netz98/n98-magerun/raw/master/autocompletion/bash/bash_complete` and then initialized it in the current shell via `. ~/.bash_completion` and it works like a charm with my OS:

- My OS: Linux user 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- My Bash: GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

So I guess this is related to the Mac OS system you're using. However I can't troubleshoot as I don't have an Apple computer, so you need to relate to existing information about bash autocomplete on apple computers and/or find out more on your own.

However from what I can see from your error message (the part you couldn't fix so far):

>     [...] paste [-s] [-d delimiters] file [...]

It looks like that the `paste` command is different on your system. Here is mine so that you can compare it:

	$ paste --version
	paste (GNU coreutils) 8.21
	Copyright (C) 2013 Free Software Foundation, Inc.
	License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
	This is free software: you are free to change and redistribute it.
	There is NO WARRANTY, to the extent permitted by law.

	Written by David M. Ihnat and David MacKenzie.


I would assume that the version of `paste` on your system is different (probably the BSD variant), but that's just an assumption. I suggest you contact an Apple System professional having profound knowledge in command-line utilities differences to linux and more GNU based systems.

**Comment by tkn98** [comment]
See as well: [How to replace Mac OS X utilities with GNU core utilities?](http://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities)

**Comment by ktomk** [comment]
@conveydk: I just wanted to keep you in the loop that wee recently updated the autocomplete file for bash. It must not be that it solves your issue, but it might be, so I thought I drop you a ping.

@cmuench: How did you manage to get autocompletion working on Mac OSX? Maybe you can leave some hint here?

I close this ticket for now as there was no traction for about exactly a year.
