### ISSUE TITLE
Cache clean "race" condition

### ISSUE THREAD

**Issue by electrawn** [netz98/n98-magerun#483]
In magerun, if I use ip addresses for the database server and change those in local.xml, when I run cache:clean config I’ll get a “no route to host” error because magerun will pull the ip address for the db server from the cache before attempting to cleaning it. 

This snippet of code below does work using array('global_ban_use_cache' => TRUE) for the init. I traced how magerun works back to the init magento1 function, however I don’t see how to easily inject global_ban_use_cache into the initsettings. This setting also only works C 1.6/E 1.11 or higher. Probably should be enabled by default for any cache clean or flush command.
```php
<?php
/**
 * Set global/skip_process_modules_updates to '1' in app/etc/local.xml and
 * then use this script to apply updates and refresh the config cache without
 * causing a stampede on the config cache.
 *
 * @author Colin Mollenhour
 */
umask(0);
ini_set('memory_limit','512M');
set_time_limit(0);
if(file_exists('app/Mage.php')) require 'app/Mage.php';
else require '../../app/Mage.php';

// Init without cache so we get a fresh version
Mage::app('admin','store', array('global_ban_use_cache' => TRUE));

// Now enable caching and save
Mage::getConfig()->getOptions()->setData('global_ban_use_cache', FALSE);
Mage::app()->baseInit(array()); // Re-init cache
Mage::getConfig()->loadModules()->loadDb()->saveCache();
echo "Saved config cache.\n";
```

**Comment by cmuench** [comment]
@electrawn 
We fixed that in the latest 1.95.0 release. Can you verify it?

**Comment by amenk** [comment]
this causes a regression: #613 This ticket seems like quite an edge case. What about adding a switch `--reinit` to the `cache:flush` for such cases?

**Comment by ktomk** [comment]
Original source of the script presented here in OP is: https://gist.github.com/colinmollenhour/2715268

IMHO the race-condition reported here is no race condition, it's a configuration issue (or question).

The reported problem (“no route to host” error) is a Magento misconfiguration. The database is not available any longer. The problem is that the database configuration has been changed without clearing / disabling the config cache first. It then might be too late (as in the given scenario) because the former database configuration is not accessible any longer and Magerun quits with an error.

The changes applied should be reverted, Magerun can only relate to the concrete configuration which might - or might not - be cached. It's up to the user to configure the system properly which includes cache invalidation, Magerun (still) can't do that for the user.

Providing a `--reinit` switch for cache:flush could be useful under certain circumstances. But it's important to keep in mind that this does not solve all configuration issues.

What's perhaps really missing is to remove the defaults cache backend (File) default cache directory (`var/cache`). In other words: `rm -rf var/cache/*`. Maybe a `cache:dir:flush` command. This could be handy for other use, too.

**Comment by ktomk** [comment]
The more I run over this (currently: `AbstractCacheCommand::banUseCache()`) I have the feeling this has only introduced regressions with little gain. I'll add the `cache:dir:flush` command in the meanwhile.
