### ISSUE TITLE
[refactoring] Extract db functions to own composer module

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#494]
The database functionality is quite big and unique and could be of use for other projects (magerun2, conrun, custom tools for other projects) almost without modification. That is why I suggest to pull it to an own composer project.

What do you think?

I might also do some work there, but then it might end up in the imi-digital namespace :-D so I give you the priority.

**Comment by cmuench** [comment]
Currently we don't like to bundle the logic into an own module. We have plans to refactor the logic in the next month.
One plan is to extract a non Magento cli base application.

**Comment by amenk** [comment]
I would like to do the following:
* Move src/N98/Magento/Command/Database/Compressor to Helper subfolder
* Pass a class with DB configuration to the helper, remove detectDbSettings
* Put DatabaseHelper into a new composer module and include it in the project

**Comment by tkn98** [comment]
When I lastly thought about that, it was because the database helper class is huge. As it's a collection of methods (more or less) the one idea I had was to extract database methods that operate on the (preconfigured) PDO database adapter, which could (but must not)  be represented by an abstract base class. Each database command offers a parametrized command which then interally deals with the database abstraction and expects plain/native PHP datatypes for input and output.

Normally the parametrized database commands themselves should be near to the command that makes use of them, but I would have out them on first sight just into one folder of their own, which is somewhat inheritting the "mistake" the helper did represent in the end. The helper only needs to make use of the factory class for the database commands and wire the command invocation.

My 2 cents, and I didn't start with that. I have some code-changes on some of the database helper methods in #621 which is not yet ready to merge but close.

**Comment by amenk** [comment]
*bump*
How are those code changes of the database functions going on? Still would like to extract the whole `src/N98/Magento/Command/Database/*` functionality... We

**Comment by amenk** [comment]
*bump* I would like to move some functionality (especially import + export) to helper classes and then extract those to an own composer module - what do you think?

**Comment by amenk** [comment]
What is the status of the git subtree sync we talked about last time we met?

**Comment by tkn98** [comment]
It's in the making. I don't yet know if we can meet tonight again, but if so I'll bring the notebook with me. It's also possible that I can push something, I did some work on this the last days.

**Comment by amenk** [comment]
cool, see you there

**Comment by ktomk** [comment]
Yesterday evening the shared folder touched both Magerun repositories in their development branch. Right now the shared repo is taken in relatively, you can find a copy of it online here: 

- https://github.com/ktomk/mr-shared

Shared code is relatively stable and I already have a small TODO what to do next so far:

- Add a README.md to the repository
- Add a travis build for the shared repo  (e.g. for starters: syntax, CS, tests)
- files.php from build/bin in MR1
- release helper script from build/bin
- Config Loader and Config

So this is open for more.

You have to do nothing special, each Magerun repository works out of the box. If you make use of the source version and have in the past, you need to run

    $ composer dump-autoload

To update the auto-loading routines for the new folder.

**Comment by amenk** [comment]
I had a look at mr-shared and it is almost empty :-) Is there any progress, i.e. on the Database functionality extraction?

**Comment by tkn98** [comment]
Actually there is one problem with it (technical) which causes the stale. But you can find shared resources in the shared folder already which is part of both projects.

**Comment by amenk** [comment]
But they are not in a separate git yet?

**Comment by tkn98** [comment]
Technically it is, but it's not yet properly shared remotely (read: on github). But we don't hide any code or so b/c thanks to subrepo, we always share all code regardless of repo. I think I can tackle with it next week, at least for the part I have in mind what could solve the technical issue. We also have a bugreport upstream but it's not so trivial to reproduce. Every start is hard :)

**Comment by amenk** [comment]
Here we go ... https://github.com/iMi-digital/n98-utils-split

**Comment by cmuench** [comment]
@amenk that's nice, but I want to have all n98-magerun code in the netz98 organization.

**Comment by amenk** [comment]
This weekend, I am trying another approach ... I extract the DB functionality to a simple PHP module (should not have a symfony dependency) 

Sure, I try to use as much code as possible from the netz98 database code.

Here is the start: https://github.com/iMi-digital/database-helper
