### ISSUE TITLE
Redis and reached 100 router match iterations problem after cache:clean

### ISSUE THREAD

**Issue by gkopec** [netz98/n98-magerun#583]
Did anyone find a problem on running cache:clean with some option, e.g:
n98-magerun.phar cache:clean block_html
n98-magerun.phar cache:clean eav layout
with Redis and Cm_Cache_Backend_Redis module? After that kind of operation I got " Front controller reached 100 router match iterations". It looks like main routers (Admin, Standard) are not on the list anymore. What's more curious when I run
n98-magerun.phar cache:clean
...it works and I can get my store without any error anymore.

I think it could be connected with AbstractCacheCommand.php->reinitCache()
\Mage::getConfig()->loadModules()->loadDb()->saveCache();

**Comment by gkopec** [comment]
It's some extension fault. Sorry for unnecessary issue.

**Comment by gkopec** [comment]
I just found that if I add "config" type e.g. 
n98-magerun.phar cache:clean block_html config
it works ok.

**Comment by tkn98** [comment]
Thank you for reporting the issue. Would you consider this a flaw? If so could you please shortly describe what the expected behavior would be and why?

**Comment by gkopec** [comment]
I think reinitCache() is clearing the config tree but it's not cleaning redis config cache. And yes, it's a problem because it shows incompatibility with Redis server. In my opinion reinitiate config cache should be done only when the config cache is on the n98-magerun.phar cache:clean list.

**Comment by convenient** [comment]
Wow! This is funny. I've done a massive write up on config cache, and clearing specific cache entries to trigger it.

https://github.com/convenient/magento-ce-ee-config-corruption-bug#replication

You are definitely able to trigger a `100 router match iteration` error by clearing specific cache entries. I was able to fix it by patching magento.

The fact that `reinitCache` is declared by calling `loadModules` and `loadDb` directly and not via the `init` functionality is definitely a warning bell. 

If possible I'd recommend hooking into the `Mage_Core_Model_Config::reinit()` functionality and seeing if that solves the issue.

**Comment by ktomk** [comment]
@convenient: What a massive write-up! I could not even read it that long :D So did you run to a similar conclusion as was reported here in this issue, I guess? And is your conclusion still that Magento core needs patching? I don't see a way to hook into `Mage_Core_Model_Config::reinit()` because  AFAIK the config model is loaded before any extension, isn't it?

**Comment by convenient** [comment]
@ktomk Damnit! It's an educational read, would definitely give a little insight into the madness going on here. ;)

There are definitely core issues that cause this error, but it is usually made worse by non-vanilla code using (sadly) unsafe publicly available methods.

I don't know much about how magerun instantiates or interacts `Mage`, but I don't see why you couldn't replace.

```
    protected function reinitCache()
    {
        if (!$this->_canUseBanCacheFunction()) {
            return;
        }

        \Mage::getConfig()->getOptions()->setData('global_ban_use_cache', false);
        \Mage::app()->baseInit(array()); // Re-init cache
        \Mage::getConfig()->loadModules()->loadDb()->saveCache();
    }
```

with

```
    protected function reinitCache()
    {
        if (!$this->_canUseBanCacheFunction()) {
            return;
        }

        \Mage::getConfig()->getOptions()->setData('global_ban_use_cache', false);
        \Mage::app()->baseInit(array()); // Re-init cache
        \Mage::getConfig()->reinit();
    }
```

`\Mage::getConfig()->reinit();` will then safely mark the object variable `_useCache` as `false` and drastically reduce the chance of saving a corrupted cache.

**Comment by tkn98** [comment]
Well well I see, I have to take a read then.Tthis perhaps might be even related to #613 / #483.

**Comment by convenient** [comment]
A quick read through those issues and my scooby doo senses agree that aggressive object caching might be part of the issue there.

**Comment by diglin** [comment]
Hi, just bring here a feedback. I got also issue with magerun and the 100 router problem by using `n98-magerun.phar cache:clean block_html` with a shop connected for backend cache with redis. In this case, I have to use the parameter cache:clean without additional parameters to clear the issue. I suppose I faced similar problem as other here. 
I cannot go deeper in details to know what's really the problem, I am little bit limited with time at the moment.

**Comment by szepeviktor** [comment]
Cleaning only `block_html` cache leaves the `config` cache empty causing this error.

**Comment by mseliger-dotsource** [comment]
Hey, i need to bring this issue up again. The problem is definitely the `reinitCache` method as mentioned by @convenient 

```
protected function reinitCache()
{
    if (!$this->_canUseBanCacheFunction()) {
        return;
    }

    \Mage::getConfig()->getOptions()->setData('global_ban_use_cache', false);
    \Mage::app()->baseInit(array()); // Re-init cache
    \Mage::getConfig()->loadModules()->loadDb()->saveCache();
}
```

This implementation will skip the magento fix mentioned [here](https://github.com/convenient/magento-ce-ee-config-corruption-bug#update-good-news-a-patch-from-magento).

### Reproduction Magento 1.14.3.10 + Redis

1. Clean full_page cache `n98-magerun.phar cache:clean full_page`
2. **While** magerun is cleaning the cache: simply access any magento page

### Workaround
We experienced this problem even with a simple cache:flush, because its related to concurrent requests.

A possible workaround for all cache clean commands (clean and flush) would be the usage of `--no-reinit` option, e.g.  `n98-magerun.phar cache:clean --no-reinit full_page`

**Comment by convenient** [comment]
I wonder whether this issue would be fixed if `reinitCache` was tweaked to be like

```php
protected function reinitCache()
{
    if (!$this->_canUseBanCacheFunction()) {
        return;
    }
    \Mage::getConfig()->reinit();
}
```

This would avoid any race conditions with the shared cache so long as the code change @mseliger-dotsource referred to is in place.

**Comment by mseliger-dotsource** [comment]
I don't think this issue is only Redis related as the problem is exactly the one mentioned in the github pages of @convenient. The problem is definitely something about locking with Magento cache lock mechanism, race conditions of this lock and Magento's strange behavior of caching parts of the config with different cache keys.

Maybe these race conditions are more likely to occur with Redis (latency vs. file write of file based cache) as our Redis heavily used.

Nevertheless i assume using `\Mage::getConfig()->reinit();` instead of the custom direct way
```
\Mage::app()->baseInit(array()); // Re-init cache
\Mage::getConfig()->loadModules()->loadDb()->saveCache();
```
in https://github.com/netz98/n98-magerun/blob/565fb3bc9d0994e2ebb3ff319d6a666946b40057/src/N98/Magento/Command/Cache/AbstractCacheCommand.php#L79 would match the Magento logic and include the bugfix.

**Comment by mwgamble** [comment]
This appears to make the change from #863 to be somewhat redundant.
