### ISSUE TITLE
Cookie Domain and Secure BaseURL (http) does not match

### ISSUE THREAD

**Issue by ehloj** [netz98/n98-magerun#584]
I am struggling to understand the output of `sys:check`

Running a multistore environment with each store configured as follows:

`Unsecure Base URL` = `https://example.com/`
`Secure Base URL` = `https://example.com/`
`Session Cookie Management Cookie Domain` = `.example.com`

What is the meaning then of this:

`✖ Cookie Domain (secure) Store: example Cookie Domain and Secure BaseURL (http) does not match`
`✖ Cookie Domain (unsecure) Store: example Cookie Domain and Unsecure BaseURL (http) does not match`

**Comment by cmuench** [comment]
This could be a bug. We check if base url contains the cookie domain. In this case it seems that we don't respect the starting dot.

**Comment by tkn98** [comment]
Depends on which RFC to support:

* [RFC6265](http://tools.ietf.org/html/rfc6265#section-5.2.3) (Apr 2011) (and [RFC2965](http://tools.ietf.org/html/rfc2965) (Oct 2000)) - `.example.com` as Cookie-Domain matches `http://example.com/`.
* [RFC2965](http://tools.ietf.org/html/rfc2109) (Feb 1997) - `.example.com` as Cookie-Domain *does not* matche `http://example.com/`.

With the following notes:

1. The date "2000" is misleading, as that RFC never made it. It's now since 2011 that this matches.
2. As of today (2015) I'd say that the error message is misleading so this qualifies as a flaw.
3. These values *should* be compared with a library that does the job, the rules are rather complex.
4. Public suffixes *should* be taken into account if modern user-agents are targetted.
5. Domain name normalization *should* be applied. This includes punycode (very recent Magento versions support Unicode domain names).

In any other case, if the first character is a dot %x2E ("."), it can be just removed and tested against (the lowercase) domain name from the base URLs for a full match for a quick fix in addition to the current check.

**Comment by tkn98** [comment]
@ehloj: The problem should be fixed in the development version. It was not easy to me to fully reproduce the issue but I could find a location in the code which was able to trigger such a flaw. 

Please try against the latest development build and let me know if this solves your issue.

To update against the unstable development version just use:

    $ n98-magerun.phar self-update --unstable

**Comment by tkn98** [comment]
@ehloj: I just added some more improvements and cookie-domain verification as well as base-url verification via `sys:check` should be much more comfortable.

**Comment by rareuropa** [comment]
Thank you for investigating this further. In the end I removed all explicit settings on my multi-store domains and reverted to default Magento session cookie settings. This solved all the problems (fingers and toes crossed) customers were having while using the store (especially using Chrome). Unfortunately I am unable to test this fix as I no longer have a functioning copy of the old store and settings. Your tool was found after much trial and error research and really helped. Many thanks.

**Comment by ehloj** [comment]
Thank you for investigating this further. In the end I removed all explicit settings on my multi-store domains and reverted to default Magento session cookie settings. This solved all the problems (fingers and toes crossed) customers were having while using the store (especially using Chrome). Unfortunately I am unable to test this fix as I no longer have a functioning copy of the old store and settings. Your tool was found after much trial and error research and really helped. Many thanks.

**Comment by ktomk** [comment]
@ehloj: Good to read you've figured a way out. For your information: The basic Magento cookie-domain setting is an empty one which delegates the domain handling to the browser based on the domain used with the request URI. This normally works well but for some versions of Internet Explorer and only if you're using a single domain so you don't care about the false settings this leads to.

A general safe suggestion regarding domain-cookie is:

- Prefix your main domain with the www - "`www.example.com`"
- Set the cookie domain to "`.www.example.com`"

This suggestion is not only safe, but it also leaves you more control for future changes in your infrastructure.

If you aim for the blind way, just leave the cookie domain empty as you don't need to configure anything. It then might or might not work with different sub-domains, so don't use different sub-domains then. Sites configured this way are easier to attack, and maintaining those sites are much more cumbersome.

From the description you give, you should make yourself comfortable with how cookies work together with domains first and then configure the system to your needs. I personally have some doubts you've got cookie problems especially with Chrome, with all due respect, that sounds a bit fishy to me.

**Comment by tkn98** [comment]
@ehloj: Just adding up: In *any* case, this is easier to verify with the updated system-check of magerun. Another command which can be useful is to search config settings with wildcards:

    $ n98-magerun.phar config:get '*cookie*'

this can come in handy for troubleshooting an installation.

**Comment by ktomk** [comment]
There were some flaws in the check in develop, I just put it under test and fixed those. merged in #611
