### ISSUE TITLE
Difference between cache:clean VS cache:flush

### ISSUE THREAD

**Issue by janw-oostendorp** [netz98/n98-magerun#588]
Quick question, title says all. What is the difference.
Can somebody explain it to me?

**Comment by fbrnc** [comment]
This is not so mage n98-magerun specific, but related to Magento that comes with those two different actions in the first place (you'll also find two buttons on the cache management page).

While `cache:clean` deletes the cache storage by tags `cache:flush` will wipe out everything.

There are two major differences here:
- some things are stored into the cache without the proper tags. `cache:clean` will not delete those. 
- other things might be using the same cache storage (this is not recommended, but sadly sometimes this is the case). Flushing the cache will result in *everything* being deleted. So if multiple Magento instances use the same cache storage or if you store your sessions in the same redis database you're using for the cache (please don't! :) then they will also be gone.

**Comment by janw-oostendorp** [comment]
Thank you, that explains a lot.

**Comment by hgati** [comment]
Thanks.

**Comment by routbiplab** [comment]
Thanks for the explanation.

**Comment by dfelton** [comment]
@fbrnc Old post but could you please elaborate on this a bit more. 

> While cache:clean deletes the cache storage by tags cache:flush will wipe out everything.

I am aware of the difference between a Cache Group, and a Cache Tag. Are you stating that `cache:clean` will only clean out *those tags which have been flagged as invalid*? 

Take for example the `Block HTML` cache group. Lets discuss two blocks `Foo`, and `Bar`.

`Foo` has the following logic it's class:

    protected function _construct()
    {
        parent::_construct();
        $this->setData('cache_lifetime', '604800'); // 7 Day TTL
        $this->setData('cache_tags', ['foo']);
    }

`Bar` has the following:

    protected function _construct()
    {
        parent::_construct();
        $this->setData('cache_lifetime', '604800'); // 7 Day TTL
        $this->setData('cache_tags', ['bar']);
    }

Then consider the following scenario:

1. HTTP Request occurs, both `Foo` and `Bar` exist on the page, each are cached as neither were in cache before.
2. Something occurs that flags the `cache_tag` `foo` to be marked invalidated. At this time, both `Foo` and `Bar` still exist in the cache. 

If someone now goes into the command line, would this be an accurate description of what is happening?

1. CLI user performs `bin/magento cache:flush block_html`:
-- Neither `Foo` or `Bar` exists in the cache now, as the entire `Block HTML` cache group has been wiped.
2. OR user performs `bin/magento cache:clean block_html`:
-- `Foo` is removed from the cache, because the block had the cache_tag `foo` added to it, and this was flagged invalidated earlier.
-- `Bar` block still exists in the cache.

**Comment by hzubyrss** [comment]
What do you think is it good to refresh config','layout','block_html','translate','collections','eav','config_api','config_api2 all cache with cron on hourly or 30min based ?

**Comment by ktomk** [comment]
@hzubyrss: neither. For production this should not be necessary and for development it is perhaps easier to disable caching or just run the leanup when needed. There is no thing as a half cleaned cache. Either it's cached or not. Btw. it is said that cache invalidation is one of the hardest thing in programming.
