### ISSUE TITLE
Verify password on (admin) user create

### ISSUE THREAD

**Issue by pquerner** [netz98/n98-magerun#622]
Creating a (admin) user is super simple on the CLI with this tool.
However, I miss the "enter your password" twice as its very common on most CLI programs.

This should of course affect the interactive mode and the parameter mode.
Both submitted passwords must be equal.

**Comment by ktomk** [comment]
Thanks for bringing up that suggestion.

You might miss it from habituation but I see (in honest personal opinion) no reason to bother a user here with asking again. Especially as the password reset sequence is really straight forward with Magerun.

So if I may ask, can you name what use such a feature would bring to the Magerun user?

Is this more a habituation thing or do you think asking for passwords twice is more secure or what is this about? Would be good if you can share that with your feature suggestion.

Are you using that command interactively? I normally use it for development setups only and then the user is created / password reset automatically via the hs:ccd command.

And can you say if you would be willing to provide a pull request or not (or if you're perhaps undecided on that)?

**Comment by pquerner** [comment]
Probably wont do much to the end user but it will not allow typos when inserting a new (admin) user. So its a security feature I would say.
And like I said, most CLI tools do have that feature - whereever theres a password it is
a) hidden from terminal
b) you have to repeat it twice (especially when creating a user/account/...)

I didnt look at the code yet, but I wouldnt say no to a PR - when I have some time.

I do use that command for setup purposes too, sometimes with parameters, sometimes in the interactive mode.

**Comment by tkn98** [comment]
There is not reason to enter a password twice for security. Actually the opposite is the case. Double entering passwords (by you said to prevent typos which typing doubly on a keyboard actually doesn't so much) was introduced for systems where reset password procedure wasn't implemented properly or even missing. As we have reset passwort, there is not use of it.

Which is why I was asking if this is about your habit as you expect it (so this could become an option for you) or you see actual reasons. Security is none to that point, as isn't usability.

Just trying to find an educated option on it so it can be said if this is useful by default (so far I'd say no for by default, just an extra option for those who whish).

**Comment by pquerner** [comment]
Ok, its settled then. Was just an idea. Great we had a talk about it. This software is here to get better over time and if this suggestion doesnt help - no hard feelings. ;)

Have a good one all.

**Comment by tkn98** [comment]
Please you to and I hope my bad english wording didn't sound too harsh. We're also absolutely open to any kind of serious or crazy feature request / issue reports. Those are all valuable. So if you have more issues, please don't stop reporting them.
