### ISSUE TITLE
Unable to manage extensions anymore

### ISSUE THREAD

**Issue by pascalblanchet** [netz98/n98-magerun#692]
I noticed today that I can no longer list, search or install any extensions via n98-magerun. It has always worked perfectly fine on the same Magento instance. Now, when I run the commands extension:list or extension:search, nothing happens, the prompt simply comes back. Adding -vvv outputs

    Load dist config
    Search for Magento in folder...
    Found Magento in folder...
    DEBUG
    Could not find package.

Nothing out of the ordinary here, besides that it normally finds the package. More importantly, extension:install doesn't do anything at all anymore.

The only affecting change I can think of in between the time it used to work and now is that I've upgraded from EE 1.14.1 to 1.14.2.1.

I was using n98-magerun v1.96.1. Upgrading to latest v1.97.5 had no apparent effect.

The same problem happens in both production and local environments. Could my IP address have been blacklisted somehow?

**Comment by tkn98** [comment]
Sorry don't know for the IP blocking. This would require some debugging I guess what's really going on. Which command line exactly did you fire? Also I fear I can't reproduce here currently.

**Comment by pascalblanchet** [comment]
Thanks for following up! I am running

    php n98-magerun.phar extension:list

This morning, I did some testing. I installed a fresh EE 1.14.1 with clean database and ran the above. It worked fine. I then upgraded the clean instance to EE 1.14.2.1 and I couldn't list extensions anymore. It appears something in between these versions is breaking it.

**Comment by ktomk** [comment]
I have tried this on a  Magento 1.9.2.1 and the command works. You can see the results on https://circleci.com/gh/ktomk/n98-magerun/143 under the "test" pane. IIRC 1.9.2.1 should be similar to 1.14.2.1. Can you use magerun from sources as well. E.g. debug/develop it on a test box to find out more with that latest magento version? I could only test this in the office and I'm in the weekend already.

**Comment by pascalblanchet** [comment]
Same here, I'll play around with the sources next week when I get the chance and will report back here.

**Comment by fabianfetik** [comment]
I just encountered the same error but I don't think this is an issue with n98-magerun since all it does to list/download extensions is use the magento cli.

To confirm please do the following:

In your magento directory try `./mage list-available`
if you're getting the error
```
Error:
list-available: Uri doesn't contain host part
```
you're most likely missing the `php5-curl` package.

On a ubuntu (debian-based) system install it with `sudo apt-get install php5-curl`

As a sidenote:
This error happened to me after installing and switching to `phpbrew` since curl doesn't seem to be part of the default package when installing php with phpbrew.
In case you still have this issue and coincidentally switched to phpbrew as well, try installing and enabling curl with phpbrew, this fixed it for me.

First use/switch to a php version with phpbrew
`phpbrew use [insert php version here]`
then `phpbrew ext install curl`

Check the build.log in case of failures, I also had the following missing dependencies:
```
sudo apt-get install autoconf
sudo apt-get install libcurl3-dev
```

**Comment by pascalblanchet** [comment]
You were right, it had to do with curl. In my case more specifically, the line:

    $this->curlOption(CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

in downloader/lib/Mage/HTTP/Client/Curl.php was the problem. changing it for:

    $this->curlOption(CURLOPT_SSLVERSION, 'TLSv1');

made Magento load extension lists once again.

Thanks!

**Comment by ktomk** [comment]
that is the binding to the underlying curl C library and that using a specific SSL backend: http://stackoverflow.com/questions/28354232/centos-6-libcurl-tlsv1-error (just from a quick online search).

**Comment by ktomk** [comment]
The problem was reported to be inside Magento 1 core. nothing to do with Magerun.
