### ISSUE TITLE
indexer dies on error

### ISSUE THREAD

**Issue by hhirsch** [netz98/n98-magerun#701]
The traditional magento indexer says An error occurred while saving the URL rewrite
and then continues. But magerun dies and does not rebuild any more indexes.

**Comment by tkn98** [comment]
@hhirsch: Sorry for this late reply and thank you for reporting this issue. Can you provide exemplary output of the commandline and it's output with the ticket? And are you able to provide additional details? Like the magerun and magento version used?

**Comment by pocallaghan** [comment]
Comparing the indexer command to `shell/indexer.php` show's that there is an additional try catch inside the for loop in the core version. Simply copying this should make the remaining indexers run as per the core indexer rather than breaking out of the loop. I'd make a pull request, but I don't have time at the moment to change and test.

**Comment by tkn98** [comment]
@pocallaghan Analysis sounds good. If you can provide a PR I can review it then and also to test. Otherwise just drop me a line and I can take a look.

**Comment by tkn98** [comment]
The `index:reindex:all` command still has this issue, it is at the point for try-catch/foreach un-aligned with the `index:reindex` command. Both commands can share of the execution code which they don't do yet.

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
