### ISSUE TITLE
cron:run -> Killed

### ISSUE THREAD

**Issue by marvinosswald** [netz98/n98-magerun#705]
Trying to execute a cronjob it gets back to me with "Killed", I guess it couldn't alloc enough memory am I right ? or is there something else what could echo "Killed" ?

**Comment by tkn98** [comment]
There can be a plethora of reasons. Check your syslog, sounds like your system killed it, syslog normally has more info.

Please let me know if this information was helpful.

**Comment by marvinosswald** [comment]
Sorry, should have closed this earlier. In my case it was just not enough memory available.

**Comment by ktomk** [comment]
@marvinosswald: Can you share if the issue was because it was with the configured default (I think that's at 128m) or just the case because you needed more memory.

I ask because it should be possible for `cron:run` to display at least the last error message in case of a fatal error (not enough memory would be such a fatal error) which would be much more helpful in such situations.

**Comment by marvinosswald** [comment]
@ktomk that system ran on one of my development virtual machines which has 1024 mb memory. So it was just my machine running out of memory. Yes a fatal error message would be much more helpful :+1:

**Comment by cmuench** [comment]
I checked this behavior in a current Magento Open Source 1.9.4.0 instance and cannot reproduce that problem.
Tried it with: `php -d memory_limit=20M n98-magerun.phar sys:cron:run`
and got got a fatal error message.
