### ISSUE TITLE
Magento downloads are no longer working from magentocommerce.com

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun#722]
Great, just discovered the url's from magentocommerce.com where you can download Magento are no longer working.
For example these ones no longer work:
http://www.magentocommerce.com/downloads/assets/1.8.0.0/magento-1.8.0.0.tar.gz
http://www.magentocommerce.com/downloads/assets/1.8.1.0/magento-1.8.1.0.tar.gz
...

I have no idea if this is a temporary glitch or not, but maybe you should start looking at using different url's for these versions.

**Comment by tkn98** [comment]
It's redirecting to the shorter domain now:

* http://magento.com/downloads/assets/1.8.0.0/magento-1.8.0.0.tar.gz
* http://magento.com/downloads/assets/1.8.1.0/magento-1.8.1.0.tar.gz

I just checked for those two, I thinks this is across the board.

**Comment by clegginabox** [comment]
@hostep check the config.yaml file, there are mirrors on Github for some versions.

For example
`n98-magerun.phar install --magentoVersionByName='magento-mirror-1.9.2.2'`

Work around whilst the URL's get updated

**Comment by chedaroo** [comment]
Also for the time being, if you can't find a mirror for the version you need then you can add your own repositories / overwrite existing ones as per the docs here https://github.com/netz98/n98-magerun/wiki/Magento-installer

**Comment by Schrank** [comment]
Just two cents from my site, there are two options, either use a github mirror (or something alike):
https://github.com/OpenMage/magento-mirror/releases, e.g.
https://github.com/OpenMage/magento-mirror/releases/tag/1.9.2.2

> Or use the [cool API (which needs an account too :-/)](http://magento.stackexchange.com/questions/28582/how-to-download-magento) 
> Thanks https://gist.github.com/piotrekkaminski/9bc45ec84028611d621e
>> 1) First you need to generate download token. Login to your account on magento.com and generate it 
>> in Account Settings->Downloads Access Token
>> 2) You will need your MAGEID as well. It is shown at the top-left in your account page.
>> 3) curl -k https://MAGEID:TOKEN@www.magentocommerce.com/products/downloads/info/help
>> 4) Profit!

**Comment by tkn98** [comment]
Problem with MAGEID is that I don't think we'll want to spread it. Perhaps a magerun-download-account, but I dunno (I know about that method, but thanks for referencing it here, too).

I'll check for the mirrors first.

**Comment by Schrank** [comment]
right, I don't want to spread it too. My intention was that magerun uses YOUR id, but then you need to configure it. This is crappy, but the official source ...

**Comment by ktomk** [comment]
YOUR id does not work well for unattended setups like we have with mage test stand and automatic builds.

and what about the sample data? any mirrors of these?

**Comment by Schrank** [comment]
at least not in the API. No clue, wether it is anywhere availabe. I would love to just run a magento mirror. But this would be as trustful as any github mirror.

**Comment by tkn98** [comment]
@Schrank: We have checksums per the files, so this is not about blind trust but controlled blind trust ;) I dunno how much traffic this creates, we could benefit from a dump because I just realized that not all the packages we have supported in magerun so far are available via token. also the demo data is not available via the token based download REST API. This is all in all quite some chaotic situation, I try to figure something out so we get it running at least again for the moment.

**Comment by erichileman** [comment]
The magerun token for downloads was suggested and shot down unfortunately: https://twitter.com/aschroder/status/659885608429481984

**Comment by fbrnc** [comment]
Since downloading from magento.com seems to be very fragile I like @clegginabox's suggestion to use Magento mirror instead. (Especially for test runs using MageTestStand the "trust" issue shouldn't be an issue :)
But currently not all magento-ce-* versions we have in n98-magerun are available as magento-mirror-*.
I created an issue for that: https://github.com/netz98/n98-magerun/issues/724

**Comment by fbrnc** [comment]
Just created tagged 1.8.0.0 in openmage/magento-mirror and created a pull request for #724 to add the that one (and 5 more that were missing) to config.yaml.

**Comment by ktomk** [comment]
Version 1.97.7 of Magerun has just been released addressing this issue. The list of mirror packages has been updated and improved. The *install* command still has **magento-ce** packages, but these do still not work. Use the **magento-mirror** packages instead, the line-up has been improved, here a short view:

* magento-mirror-1.9.2.2
* magento-mirror-1.9.2.1
* magento-mirror-1.9.2.0
* magento-mirror-1.9.1.1
* magento-mirror-1.9.1.0
* magento-mirror-1.9.0.1
* magento-mirror-1.9.0.0
* magento-mirror-1.8.1.0
* magento-mirror-1.8.0.0
* magento-mirror-1.7.0.2
* magento-mirror-1.6.2.0
* magento-mirror-1.5.1.0
* magento-mirror-1.4.2.0

These packages are provided by Github.

The *data-sample* packages are now served from a mirror, too. These have been off-loaded into Sourceforge File Release System (FRS) which even offers automatic mirrors across the globe.

At this moment it's hard to say how long this will be the status quo. At least it's now possible to *use* unattended installs again despite some configuration changes like the name-change are necessary.

**Comment by arosenhagen** [comment]
FYI see comments on https://gist.github.com/piotrekkaminski/9bc45ec84028611d621e
I managed to get [magedownload-cli](https://github.com/steverobbins/magedownload-cli) working within our [MageTestStand](https://github.com/ffuenf/MageTestStand) with encrypted env vars on travis - but for < 1.9.0.0 we still have to rely on OpenMage mirrors since they're not available through the new API.
