### ISSUE TITLE
Phar error

### ISSUE THREAD

**Issue by mgeoffray** [netz98/n98-magerun#735]
Hello,
since last update (ver. 1.97.7) I have an error when I try to download a new version of Magento

```bash
$ n98-magerun.phar install

                        
  Magento Installation  
                        

[1]  magento-ce-1.9.1.1
[2]  magento-ce-1.9.1.0
[3]  magento-ce-1.9.0.1
[4]  magento-ce-1.8.1.0
[5]  magento-ce-1.8.0.0
[6]  magento-ce-1.7.0.2
[7]  magento-ce-1.6.2.0
[8]  magento-mirror-1.7.0.2
[9]  magento-mirror-1.6.2.0
[10] magento-mirror-1.5.1.0
[11] magento-mirror-1.4.2.0
[12] mageplus-master
Choose a magento version: 1
Enter installation folder: [./magento]
  - Installing magento-ce-1.9.1.1 (1.9.1.1)
    Downloading: 100%         
internal corruption of phar "/Users/matt/Sites/test/magento/_n98_magerun_download/98f09f2c591f13b1c32f70c0f73497cd.gz" (__HALT_COMPILER(); not found)
```
My PEAR version
```bash
$ pear version
PEAR Version: 1.10.1
```

I don't really know if that is an error from n98 or my environment, that is why I prefer asking here if somebody already have this error.

Thank you,
Matthéo Geoffray

**Comment by ktomk** [comment]
@mgeoffray: Thanks for the report. I can not reproduce your exact case on a stable 1.97.7 build (from master as well as from http://files.magerun.net/n98-magerun-latest.phar).

However regardless of me not being able to reproduce *currently **all***  `magento-ce-...` do not work. You should actually see a message like the following:

> The checksum verification of the file failed (downloaded from http://www.magentocommerce.com/downloads/assets/1.9.1.1/magento-1.9.1.1.tar.gz)

which is because magento does not offer the downloads any longer.

So please check if you really have got the latest version and/or you've your own downloads added (possible via configuration files). Also I suggest to use `magento-mirror-...` packages which are available now with all those versions.

For reference please see how I tried to reproduce:

	$ wget http://files.magerun.net/n98-magerun-latest.phar
	--2015-11-27 20:07:53--  http://files.magerun.net/n98-magerun-latest.phar
	Resolving files.magerun.net (files.magerun.net)... 5.35.244.165
	Connecting to files.magerun.net (files.magerun.net)|5.35.244.165|:80... connected.
	HTTP request sent, awaiting response... 200 OK
	Length: 2790197 (2,7M) [application/octet-stream]
	Saving to: ‘n98-magerun-latest.phar’

	100%[=============================================================================================================================================================================================>] 2.790.197   3,91MB/s   in 0,7s   

	2015-11-27 20:07:54 (3,91 MB/s) - ‘n98-magerun-latest.phar’ saved [2790197/2790197]

	$ php -f n98-magerun-latest.phar -- install

							
	  Magento Installation  
							

	[1]  magento-ce-1.9.1.1
	[2]  magento-ce-1.9.1.0
	[3]  magento-ce-1.9.0.1
	[4]  magento-ce-1.8.1.0
	[5]  magento-ce-1.8.0.0
	[6]  magento-ce-1.7.0.2
	[7]  magento-ce-1.6.2.0
	[8]  magento-mirror-1.9.2.2
	[9]  magento-mirror-1.9.2.1
	[10] magento-mirror-1.9.2.0
	[11] magento-mirror-1.9.1.1
	[12] magento-mirror-1.9.1.0
	[13] magento-mirror-1.9.0.1
	[14] magento-mirror-1.9.0.0
	[15] magento-mirror-1.8.1.0
	[16] magento-mirror-1.8.0.0
	[17] magento-mirror-1.7.0.2
	[18] magento-mirror-1.6.2.0
	[19] magento-mirror-1.5.1.0
	[20] magento-mirror-1.4.2.0
	[21] mageplus-master
	[22] my-magento-file-package
	Choose a magento version: 1
	Enter installation folder: [./magento]
	  - Installing magento-ce-1.9.1.1 (1.9.1.1)
		Downloading: 100%         
	The checksum verification of the file failed (downloaded from http://www.magentocommerce.com/downloads/assets/1.9.1.1/magento-1.9.1.1.tar.gz)

As the list of downloads shows the mirrored versions is greatly extended (ignore `[22]` which is a test configuration on my box).

I hope this information helps already. Pear version should be unrelated. Please check if you've got the latest stable version (really) because your list of install packages looks too short to me. It's probably just a borked setup or configuration.

**Comment by mgeoffray** [comment]
Hello ktomk,

with your example and a fresh download that solved my problem !
Maybe an corrupted file when I ran self-update...

Anyway thank you for your quick help and answer !
I close this issue.


Matthéo Geoffray.

**Comment by ktomk** [comment]
@mgeoffray That's great to read!
