### ISSUE TITLE
Inconsistencies between linux users after self-update

### ISSUE THREAD

**Issue by robbieaverill** [netz98/n98-magerun#753]
I had version 1.97.7 installed in `/usr/local/bin/`, owned by the main AWS user `ec2-user`.

I tried to update it to the latest version:

```
$ n98-magerun.phar self-update

  [Composer\Downloader\FilesystemException]                                                                      
  Filesystem exception:                                                                                          
  n98-magerun update failed: the "/usr/local/bin" directory used to download the temp file could not be written  

self-update [--unstable]
```

I assumed this is because `/usr/local/bin` is owned by the root user. So I run the command as root:

```
$ sudo !!
...
```

The installation was successful, however I did not see the update reflected when calling as `ec2-user`, but it does show when I run as root:

```
$ n98-magerun.phar --version
n98-magerun version 1.97.7 by netz98 new media GmbH

$ sudo n98-magerun.phar --version
It's not recommended to run n98-magerun as root user
n98-magerun version 1.97.10 by netz98 new media GmbH
```

**Question:** is there a folder somewhere that I need to `chown` back to `ec2-user` to reflect the update? I probably shouldn't be "running n98-magerun as root user" as is suggested, but I'm working with a previous install here.

**Comment by ktomk** [comment]
The recommendation to not run Magerun as root is because of access rights with the Magento web-application. E.g. when Magerun triggers some Magento API that creates files or directories, those then would be owned by root. Next to security implications, this often causes problems with access-rights on files and folders as the application normally runs under a user different than root, for example www-data.

In the situation of an update, this is a different story. When Magerun is installed system-wide (for example in `/usr/local/bin`) the operation to install the file at that location normally requires root-user-privileges.

The situation you describe having two different executables (1.97.10, 1.97.7) for two different users (root, ec2-user).

Resolve the path to the executable on your system for both users to see which file is for which user. I assume there is some difference which puzzles you a bit. But there is no magic folder or something, Magerun only has this one `n98-magerun.phar` file that is keeping the version number. And as you have two version numbers, this is a strong sign that you have two files. Try as well with the full-path to the executable to find out.

**Comment by robbieaverill** [comment]
Thanks @ktomk 

Aww - shucks - you're right :)

```
$ whoami
ec2-user
$ which n98-magerun.phar
/usr/local/bin/n98-magerun.phar
$ sudo which n98-magerun.phar
/usr/bin/n98-magerun.phar
```

Thanks for your help.
