### ISSUE TITLE
Magento 1.9.2.3 over install

### ISSUE THREAD

**Issue by aliuosio** [netz98/n98-magerun#758]
Can Someone tell me when the Version 1.9.2.3 can be installed over Magerun

**Comment by ktomk** [comment]
I'll put it into the development version in some minutes. It will contain the magento mirror version as package. I also offer the checksums for the package from magentocommerce.com:

~~~
openmage-1.9.2.3.zip 37299355 bytes
SHA: 8a93762d4897203dd77e3a527887199f66620678
MD5: 922bc8ae12bb24e436c0627da1b7a615

magento-1.9.2.3-2016-01-20-03-02-19.tar.gz 24266578 bytes
SHA: 95d2c61786764e047ab4fe60993b8d5897211aee
MD5: 99a264013d37dae48873ec0b42c83683
~~~

Btw., if you're in a hurry and can't wait until magerun has updated, you can easily add the package your own. It works by creating entries in your local magerun configuration yaml file pointing to a package. References:

* install from a Magento core zip file located on local drive instead of downloaded? (#615) 
* install from local source (#726)

Ref: #722

**Comment by ktomk** [comment]
It is now part of the development version. The version is `magento-mirror-1.9.2.3`. Thanks to [OpenMage magento mirror](https://github.com/OpenMage/magento-mirror) for keeping track and care.

It will then become part of the next stable release. There is no ETA for the next stable yet.

**Comment by ktomk** [comment]
@aliuosio: Please let me know if this solves your issue.

**Comment by ktomk** [comment]
The changes are in release 1.97.11 which just went out.

**Comment by aliuosio** [comment]
@ktomk: thanx for the support. that was more than enough. :-)
