### ISSUE TITLE
Install command missing

### ISSUE THREAD

**Issue by milansimek** [netz98/n98-magerun#759]
In the latest versions the install command is missing.

I downloaded version 1.97.7 now which still has it.

Is this a bug or by design?

**Comment by ktomk** [comment]
That is a clear sign that on your system the PHP function [`exec`](http://php.net/exec) is not available. Unless that *exec* function  is available The install command is disabled.

So this is by design, but until we found out what the exact cause in your situation is, we technically can't say if it's a bug or a feature :)

Ref:  #741

**Comment by tkn98** [comment]
@milansimek: Can you please provide the information if the PHP  `exec` function is available the environment you use Magerun?

**Comment by milansimek** [comment]
Indeed it turned out that the exec function was disabled. I noticed this when running the install command using the older n98-magerun version.

Thanks for the help!
