### ISSUE TITLE
n98-magerun.phar install - undefined constant STDIN

### ISSUE THREAD

**Issue by hanuman42** [netz98/n98-magerun#761]
I do not think this is a problem of n98-magerun.
But of my not truly understanding...
Please shed some light on me.

I used _n98-magerun.phar install_ to start the magento installer as in https://github.com/netz98/n98-magerun/wiki/Magento-installer.
But the interactive shell program, that let me choose the magento version got caught in a loop.

Is this some settings of my server?
n98-magerun.phar is located at /html

`pxxxxxx:/html > n98-magerun.phar install

                        
  Magento Installation  
                        

[1]  magento-ce-1.9.1.1
[2]  magento-ce-1.9.1.0
[3]  magento-ce-1.9.0.1
[4]  magento-ce-1.8.1.0
[5]  magento-ce-1.8.0.0
[6]  magento-ce-1.7.0.2
[7]  magento-ce-1.6.2.0
[8]  magento-mirror-1.9.2.3
[9]  magento-mirror-1.9.2.2
[10] magento-mirror-1.9.2.1
[11] magento-mirror-1.9.2.0
[12] magento-mirror-1.9.1.1
[13] magento-mirror-1.9.1.0
[14] magento-mirror-1.9.0.1
[15] magento-mirror-1.9.0.0
[16] magento-mirror-1.8.1.0
[17] magento-mirror-1.8.0.0
[18] magento-mirror-1.7.0.2
[19] magento-mirror-1.6.2.0
[20] magento-mirror-1.5.1.0
[21] magento-mirror-1.4.2.0
[22] mageplus-master
Choose a magento version: PHP Notice:  Use of undefined constant STDIN - assumed 'STDIN' in phar:///html/n98-magerun.phar/vendor/symfony/console/Helper/DialogHelper.php on line 117
PHP Warning:  fgets() expects parameter 1 to be resource, string given in phar:///html/n98-magerun.phar/vendor/symfony/console/Helper/DialogHelper.php on line 120
 Aborted 
[1]  magento-ce-1.9.1.1
[2]  magento-ce-1.9.1.0
[3]  magento-ce-1.9.0.1
...`

**Comment by tkn98** [comment]
The PHP constant [`STDIN` is a CLI specific constant](http://php.net/manual/en/features.commandline.io-streams.php), that means, it is available when you execute Magerun with the commandline version of the PHP interpreter.

Please check if the PHP command you make use of is for PHP CLI and if not, locate the path to the PHP CLI binary on the system you want to run Magerun on.

Then call n98-magerun.phar by the interpreter directly:

    $ /path/to/php-cli -f /path/to/n98-magerun.phar -- --version

For example should show the version of Magerun. This *might* already solve your problem. Please try.

**Comment by hanuman42** [comment]
:) 
yes that solved my problem.

when I use this command it works.
`pxxxxxx:/html > php_cli n98-magerun.phar install`

or at least it shows me the versions and waits for my input

thank you.
do I have to write php_cli every time I want to use magerun?
or can I set an alias or something like that?

**Comment by ktomk** [comment]
Yes you will have to. If I needed to guess, I'd say the site is hosted by *Mittwald*. Be careful, often there are more incompatibilities. Not only for Magerun but also for other PHP applications like Magento itself.

    pxxxxxx:/html > php_cli -f n98-magerun.phar -- install

For the moment you could create yourself your own `n98-magerun`  command as a bash script, put it into the path and make it invoke Magerun the way you need it.

    #!/bin/bash
    php_cli -f /path/to/n98-magerun.phar -- "$@"

If you name such a shell-script `n98-magerun`  and make it executable (see `chmod +x`) and place it within your path, you then can just type in the command-name only and Magerun will be executed.

And thanks for your report, I add that constant to the list of precondition checks, I was not aware of it yet.

**Comment by hanuman42** [comment]
not sure if I should answer (you closed this already).
But thank you both for your answers.

Yes you are right it is hosted by _Mittwald_.
Right now I am not happy that it is, cause you said there would probably be more incompatibilities even with Magento itself.
I hope I will be able to run Magento with no problems ... after all they sell Magento-Hosting.

**Comment by ktomk** [comment]
You can always answer, even on closed issues. It's just that the job "is done" that's why it's closed.

I don't want to scare you away from *Mittwald*, it's just that when you experience something that sound fishy, check the compatibility requirements a Magento system must have so that Magento runs well. I just would not take marketing speak for a given. For example as you've learned that the PHP executable isn't the one of CLI but the one of CLI, this is also true when cron is invoked etc.. It's just that you need to take some extra care and double check requirements are fulfilled. First of all your Magento installation will run on Mittwald, when it comes into the details, you have to see if they still fulfil all your needs and how much you can afford for taking care of sysadmin and sysconfig whoes (IIRC the ps command is used in cron.sh but Mittwald does not provide it - just to give you an example). But that does not belong here, you can normally find help in a hosters users-helping-users forum or other support venues of the hoster.
