### ISSUE TITLE
PHPUnit/TestCase.php cannot be used for addons

### ISSUE THREAD

**Issue by JeroenBoersma** [netz98/n98-magerun#780]
Because of the use of the hardcoded path to the `autoload.php` on `src/N98/Magento/Command/PHPUnit/TestCase.php:63` it cannot be used in addons.

If you develop and want test a addon you would like to use the existing `\N98\Magento\Command\PHPUnit\TestCase` to test your commands.
Maybe it would need some checking like the `src/bootstrap.php` already has.

**Comment by JeroenBoersma** [comment]
Already found it, there's defined `PHPUNIT_COMPOSER_INSTALL`
Will create a pull request :)

**Comment by JeroenBoersma** [comment]
Linked #781

**Comment by ktomk** [comment]
Thanks for bringing this issue up!

I could quickly take a look. As I understand it, `PHPUNIT_COMPOSER_INSTALL` is "only" available if Phpunit is installed via Composer and the binary shipped with that package is used.

The [line you suggest to change](https://github.com/JeroenBoersma/n98-magerun/commit/03639987bd1235bc10e5f26d534e4c5e7c178612#diff-4a2baa0b85ca0e7633fcb56a7baa5d4dL63) contains the autoloader not of a sub-package (Phpunit) but the main package (N98-Magerun).

This is normally not a problem because Phpunit checks packages further up as well (e.g. your change would work for me as well as I do use Phpunit from within the project).

Most likely the correct autoloader should be initialized as a Phpunit bootstrap, that would be my first tendency as well (as your initial report suggests as well).

Maybe you can elaborate a little into which concrete problem you did run? What have you tried? What did you expect? What happened instead?

**Comment by JeroenBoersma** [comment]
I understand your feedback, I'm want to add testcases to a Magerun addon, so in this case the addon is the mainpackage when I develop. I initialize the package with `composer install` and phpunit, n98-magerun are installed in that vender directory. I'm not developing within the Magerun repository directly.

I would like to use the command testcase to verify my command is working fine so I can automate things when development evolves.

If I want to use the same `\N98\Magento\Command\PHPUnit\Testcase` class as you do to test commands I get an error because the vender directory is inside my package and not within yours :)

The testcase already depends on `PHPUnit` so it can easily be changed to work in both worlds.
I'll push again to the develop branch and link the PR, maybe this explains a bit more.

**Comment by JeroenBoersma** [comment]
Linekd #782

**Comment by ktomk** [comment]
Okay, now I see, the testcase class is written in a way that it is only useful in a root-package. This is not the case in your case.

The common way to solve this is to test for the non-root-package scenario as well and make the inclusion conditional.

Could you share the relative path prefixed with `__DIR__` that would work in your case?

**Comment by JeroenBoersma** [comment]
I can add a check `if(defined('VAR'))` to make sure that I do not break anything.
But I made the assumption based on that the class was already depending on PHPUnit classes, so technically it wouldn't break and work in both cases and we wouldn't need to have duplicate code.

Let me know what you think.

**Comment by tkn98** [comment]
For backwards compat an `is_defined` check sounds reasonable to me. Additionally even if that constant is not set (or you ignore that condition in full), it should work with another hard-encoded one IMHO. Just in case phpunit becomes a dev dependency (if it isn't yet).

**Comment by JeroenBoersma** [comment]
Will change it
:+1:

**Comment by JeroenBoersma** [comment]
Did change my PR

**Comment by ktomk** [comment]
Fixed, see https://github.com/netz98/n98-magerun/pull/782#issuecomment-191680167
