### ISSUE TITLE
Remote Commands

### ISSUE THREAD

**Issue by kalenjordan** [netz98/n98-magerun#84]
One of the things that I've been using myself and considering contributing a bit of are commands that are designed to be used in a local development environment when interacting with a remote environment over SSH.

For example, a `remote:shell` command that would open up an SSH shell to the server in a similar way that `db:console` does.  Also things like a remote mysql dump similar to the local `db:dump` command.

I wasn't really sure if that was something that would really make sense for this project in general and I should just keep it in my own private fork.

At the moment, I'm just storing ssh host name locally in my own local project-specific file, but I would probably need to figure out a clean way to store them in app/etc/n98-magerun.yaml

**Comment by barryvdh** [comment]
I could see the benefit of configuring a remote connection and be able the get a stripped dump of the database. Sure you could ssh to the server, make the export there and transfer it to your local machine, but it does seem useful to be able to do that directly.

Not sure if it would be useful for all commands (because you don't accidentally want to run any command on your production server).
