### ISSUE TITLE
config.yaml - magento 1.x.x.x source moved permanently

### ISSUE THREAD

**Issue by dermatz** [netz98/n98-magerun#841]
The Magento Zip was moved permanently.
The magerun command `install` was'nt able to download the files.

See config.yaml:179

**Comment by ktomk** [comment]
Yes those are URLs like:

- http://www.magentocommerce.com/downloads/assets/1.9.2.1/magento-1.9.2.3.zip (magento-ce-1.9.2.4)

These do not work since longer, maybe it's useful to remove them. Use the mirror instead:

- https://github.com/OpenMage/magento-mirror/archive/1.9.2.4.zip (magento-mirror-1.9.2.4)

Also just seeing by that listing, the number in the file would have even been wrong :).

The problem is already known: #832 , it even is known older than that report, actually quite some time.

Related is  #812 as well.
