### ISSUE TITLE
FR: allow environment variables in local.xml

### ISSUE THREAD

**Issue by arosenhagen** [netz98/n98-magerun#851]
We currently move our deployment workflow to [envoyer.io](https://envoyer.io). For this to work we developed [Ffuenf_ConfigDotEnv](https://github.com/ffuenf/Ffuenf_ConfigDotEnv) to allow environment variables in local.xml which are loaded via [php-dotenv](https://github.com/vlucas/phpdotenv).
With this in place the n98-magerun db:* commands no longer work since the substitution takes place inside of magento.
To get this going it'll be nice to extend [DbSettings](https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/DbSettings.php#L88) to allow environment variables in local.xml database settings (see [the implementation](https://github.com/ffuenf/Ffuenf_ConfigDotEnv/blob/master/app/code/community/Ffuenf/ConfigDotEnv/Model/Config/Element.php#L29) for directions).

**Comment by tkn98** [comment]
With the implementations, I don't understand for what the library is required? The whole substitution logic takes place here:

        $value = parent::xmlentities($value);
        if (substr($value, 0, 1) == "$") {
            $value = getenv(substr($value, 1));
        }

(leaving aside that error checks are missing with this code)

I just write because this is pretty straight forward I guess.

And is there any reason the variables are substituted when the file is placed into the environment?

**Comment by arosenhagen** [comment]
The library is only required to use a .env file with environment variables (which is a default logic on envoyer.io). You're absolutely right - the whole logic is in the snippet you mentioned.
What do you mean by _And is there any reason the variables are not substituted when the file is placed into the environment?_ ?
Just did a quick PR (not tested!)

**Comment by ktomk** [comment]
When you copy the file over onto the target system, why don't you substitute the variables directly so that it won't need to be done when the application parses the file.

Right now, you're effectively breaking the file format with these place-holders. Normally you ship a template of such configuration files and on deployment, the placeholders are replaced. In your case evaling the file contents within shell should already do it.

The problem I see with the change is that values starting with `$` are unknown to be an environment variable or just a value starting with `$`.

What qualifies as a proper variable name? That could help to reduce false-positives.

I think it's better to write environment variables enclosed in angle brackets as well:

    ${SECRET_KEY}

My suggestion: Limit variable names to A-Z (uppercase) and underscore "_". Must start with letter, must be at least three characters long (in name), must not end with "_". Maximum of one "_" after each other, and letter parts minimum length of three.

    ~^\$\{[A-Z]{3,}(?_[A-Z]{3,})*}$~

Using `preg_replace_callback` should do this incl. correct checking of string lengths then.

These are just suggestions. Your feedback welcome esp. how far you can go, e.g. do you have "`${NAME}`" supported? From the example-file you gave you haven't. I know that bash and docker do it this way.

I also suggest to keep the original value w/o any substitution, if the environment variable is not set.

And please check if you can't substitute before the file is read the first time.

**Comment by arosenhagen** [comment]
@ktomk thanks for your input! That got me on the right track for this :-)
Overall it's indeed way better (and secure) to substitute those env vars on deployment. I was just in the loop of the envoyer.io logic - but after all I only had to add an appropriate update hook:
```
source {{project}}/.env
eval "echo \"$(cat {{release}}/public/app/etc/local.xml)\"" > {{release}}/public/app/etc/local.xml
```
_(taken from [replace-environment-variables-in-a-file-with-their-actual-values](https://unix.stackexchange.com/questions/294835/replace-environment-variables-in-a-file-with-their-actual-values) may be even simpler if envsubst is available)_

This will evaluate and write back to local.xml the env vars provided by envoyer.io (.env respectively) and keeps all subsequent logic. So no need to add anything to n98-magerun at all.

**Comment by tkn98** [comment]
Great to read that. it's also often common for some to have the config template like .dist and then "copy over" to the real name:

    app/etc/local.xml.dist -> app/etc/local.xml

So you can keep the other file git-ignored and the template under version control. But that just as a note in the margin.

I think it's okay to close for now.
