### ISSUE TITLE
Unable to download file

### ISSUE THREAD

**Issue by Vinai** [netz98/n98-magerun#876]
Installing magerun according to the documentation using the following commanda

```
curl -sL https://files.magerun.net/n98-magerun.phar -o /usr/local/bin/n98-magerun
chmod 0755 /usr/local/bin/n98-magerun
```

causes the an endless loop of it's re-downloading itself from the same URL until the stack blow.

```
Info: Magerun has not been downloaded yet, downloading it ...
Info: Download done, executing it with original parameters ...
Info: Magerun has not been downloaded yet, downloading it ...
Info: Download done, executing it with original parameters ...
Info: Magerun has not been downloaded yet, downloading it ...
...
```
As it turns out, the file at https://files.magerun.net/n98-magerun.phar is the same as https://github.com/netz98/n98-magerun/blob/master/n98-magerun.phar..

```
curl -sL https://raw.githubusercontent.com/netz98/n98-magerun/master/n98-magerun.phar |  md5
curl -sL https://files.magerun.net/n98-magerun.phar | md5
```

Both have a md5 hash of `d5fc665281a8efcfca17c3d38495dc57`.

**Comment by Vinai** [comment]
PS: Two days ago it still seemed to be fine.

**Comment by lukevers** [comment]
I'm also having this problem.

**Comment by ktomk** [comment]
The build is broken again ... . Thanks for the report. We'll take care.

Maybe if the unstable version is not broken you can use it instead, they are pretty close right now.

**Comment by cmuench** [comment]
I have recreated the phar file manually. Can anyone try again?

**Comment by ktomk** [comment]
Checksums now differ:

	$ curl -sL https://raw.githubusercontent.com/netz98/n98-magerun/master/n98-magerun.phar |  md5sum
	d5fc665281a8efcfca17c3d38495dc57  -

	$ curl -sL https://files.magerun.net/n98-magerun.phar | md5sum
	d3e27d8a72bcfb63f6ca512d7117cf0d  -

I'll take care of the build so to iterate over it again.

**Comment by Vinai** [comment]
As an intermediate solution I'll try to use a local old copy of magerun in the builds, but it would be great if you could put the right file back to the file.magerun.net location please.

**Comment by Vinai** [comment]
Thanks for the quick resolution!

**Comment by ktomk** [comment]
@Vinai  should be working now again. We also took some precautions so that in this manner won't happen again. Never thought of this error edge case.

**Comment by Vinai** [comment]
Yes, can confirm it works again!

**Comment by ktomk** [comment]
@tim-reynolds: Can't reproduce for

~~~
$ curl -sL https://files.magerun.net/n98-magerun.phar -o n98-magerun.phar && php -f n98-magerun.phar
~~~

Which error are you getting? The loop as reported in the first comment?

**Comment by tim-reynolds** [comment]
@ktomk Oh I am sorry, no not a loop, the error one of my team was reporting was: 

```
vagrant@dev:/var/www/html$ magerun
Info: Magerun has not been downloaded yet, downloading it ...
PHP Warning:  md5_file(n98-magerun.phar): failed to open stream: No such file or directory in /usr/local/bin/magerun on line 13
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/magerun:0
PHP   2. md5_file() /usr/local/bin/magerun:13
Error downloading magerun phar file
Please install manually from ‘https://files.magerun.net/n98-magerun.phar'```

We download magerun during provisioning and move it to /usr/local/bin as just 'magerun'

I haven't personally looked into it. I should have more thoroughly read the initial report here. I searched the issues for the primary error message.

**Comment by ktomk** [comment]
@tim-reynolds: That error description sounds like this is downloading the phar from Github. This is discouraged, use the files.magerun.net URL instead (the one given in the error message).

Background:

Question: Why is it discouraged to download the Magerun .phar file from Github? 

Answer: A long time ago, the Magerun Github repository had the binary .phar file checked into the repository. Whenever a new release was made, the repository needed a larger update as the file had many changes. Over time the phar file also grew in size. In the end the repository got more and more bloat. As it turned out, it was a bit short-sighted to distribute a phar file via the source repository.

To not break the common downloading, the phar file in the Repository has been replaced with a stub that downloads from the new location where compile phar files are offered for download: The *files.magerun.net* server.

That stub is quite rough code, it expects to be installed as `n98-magerun.phar` and then replaces itself with the latest version.

This fails in the scenario you show, the self-check (to prevent an endless download loop) fails b/c the basename is just `magerun`. So technically you report an error that is fix-able *however* it's not recommended to install via that stub anyway.

Instead just grab the version from files.magerun.net or build the phar your own from sources (the repository comes with all build-scripts in the source version and the build is reproducible, so this is actually a viable option).

In your case most likely exchanging the download URL for the provisioning should be fine.

Let me know if this solves your issue.

**Comment by tim-reynolds** [comment]
@ktomk Thanks for the fast response. Yes, we were definitely going straight to GitHub, and yes changing that fixed out problem. We are in the process now of updating all of our vagrant environment scripts to no longer pull from GitHub. Really helped us out here. :)
