### ISSUE TITLE
add -A option for db:console command (mysql --no-auto-rehash or -A)

### ISSUE THREAD

**Issue by AcousticRand** [netz98/n98-magerun#878]
If I use n98-magerun db:console, I will get a message that says:
"Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A"

And this will cause a significant delay before I can interact with the database (sometimes, on large DBs and servers that host many databases, it will pause for more than a minute).

This behavior also happens when you attempt to do some of the admin:user functions.

It would be great if we could have an option that would essentially send the "-A" or "--no-auto-rehash" option to/through the mysql client, so that those massive delays can be avoided.

**Comment by AcousticRand** [comment]
As a workaround, you can make a local (in linux, ~/.my.cnf) my.cnf file,
and either create the [mysql] section or, if it already exists, you can add the option: "no_auto_rehash" option, i.e.:
```
[mysql]
no_auto_rehash
```

**Comment by AcousticRand** [comment]
I've done what I think needs to be done to get this inserted (at least for db:console at this moment).
I am unsure, however, how to build this thing.  Are there instructions on the local build process so I can test locally?

**Comment by ktomk** [comment]
You can run against your source version by executing

    bin/n98-magerun --version

If you want to make yourself a local magento installation next to it (for testing purposes), you can execute the local setup srcipt:

    build/local/test_setup.sh

If you have a mysql database server running that can be accessed with user *root* and no password it should do everything for you. otherwise see that test_setup.sh script and edit the variables (no parameters yet). It should be straight forward.

If you want to test building the phar-file just execute the build script:

    ./build.sh

It will build the phar from the most recent commit that is checked out in your git working directory. If you did not commit changes, they are not part of the phar file.

To run the test-suite call

    vendor/bin/phpunit

Hopefully most of those commands work more or less out-of-the-box. If you run into any problems, just report back. Also if you file a pull request, we run testsuites and builds on Travis automatically as well.

**Comment by tkn98** [comment]
We believe that the feature requested is now part of the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
