### ISSUE TITLE
SHA256 mismatch on brew install

### ISSUE THREAD

**Issue by hans2103** [netz98/n98-magerun#885]
```
$ rm -rf  /Users/example/Library/Caches/Homebrew/n98-magerun-1.97.22.phar;brew install n98-magerun
==> Installing n98-magerun from homebrew/php
==> Downloading https://files.magerun.net/n98-magerun-1.97.22.phar
######################################################################## 100,0%
Error: SHA256 mismatch
Expected: 199dd0d416260c68e691580ffd3f7a448d60f616529aadadcfee584992d6253e
Actual: 15cae8e72121991fcc397ea3c3735d67f679b499e76dd427b7bd23dde05dc166
Archive: /Users/example/Library/Caches/Homebrew/n98-magerun-1.97.22.phar
To retry an incomplete download, remove the file above.
```

**Comment by ktomk** [comment]
Please report this with brew. Looks like the file has changed and brew provides an outdated checksum. Please leave a cross-link to the upstream issue here.

**Comment by tkn98** [comment]
I just pushed some changes and updated our build server so that the creation of the phar files - which were not - are not reproducible. That is, the same git revision has to create the same phar file. This is new an just in the develop branch, so keeping fingers crossed we're through with it, starting with 92ad7a3d4b049e06760e5888801ee5660e843b66.

That means in light of the reported issue that with the currently released 1.97.28 version the version mismatch should become actually saying. Before that version, released phar files could not be verified via checksums, only when checksums were generated fresh (e.g. manual download from files.magerun.net, manual comparison of the hash).

**Comment by tkn98** [comment]
@hans2103: Thanks for bringing up this issue. We believe this is solved now in the development version which is directly becomming a new release. However we can not activate this retro-actively w/o rebuilding all phar files which would change their hashsums anyway.

I close for now as I think this is as far as we get for the moment, feel free to add additional feedback, in case this is not yet working properly or we've overlooked something, we can re-open.

**Comment by ktomk** [comment]
Adding some references:

- https://github.com/Homebrew/homebrew-php/pull/3865

- #829

The brew formula needs update in their repo, from what I could see the last days, hashes are stable now.

- https://github.com/martinboy/homebrew-php/blob/master/Formula/n98-magerun.rb

- https://github.com/martinboy/homebrew-php/blob/master/Formula/n98-magerun2.rb

**Comment by hans2103** [comment]
working like a charm. Thank you
