### ISSUE TITLE
index:reindex:all dispatches wrong events

### ISSUE THREAD

**Issue by viktorsteinwand** [netz98/n98-magerun#892]
After the executing reindexing all the file `var/locks/reindex_full.lock` is still present and disallow to execute full reindex again.

Assumption is that the ReindexAllCommand (https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Indexer/ReindexAllCommand.php) dispatches wrong events in the end of the `execute` method (https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Indexer/ReindexAllCommand.php#L68):

Proposal to replace the affected lines through:

`
                Mage::dispatchEvent('shell_reindex_finalize_process');
            } catch (Exception $e) {
                Mage::dispatchEvent('shell_reindex_finalize_process');
                echo $e->getMessage() . "\n";
`

**Comment by tkn98** [comment]
Ouch, this needs a fix. Thanks for the report.

**Comment by tkn98** [comment]
We believe that the bug reported is fixed in the stable version. It can be upgraded to it using the `self-update` command.

The fix was done while changing the underlying code for #701  (in https://github.com/netz98/n98-magerun/commit/b997b5b41e21136500cb525ba0d79c6cfd16c792#diff-7b2902c94dc722cabb65f74fdbac912bR159).
