### ISSUE TITLE
Combined module xml is not handled

### ISSUE THREAD

**Issue by szepeviktor** [netz98/n98-magerun#961]
```xml
<config>
    <modules>
        <AddThis_SmartLayers>
            <active>true</active>
            <codePool>community</codePool>
        </AddThis_SmartLayers>
        <AddThis_SharingTool>
            <active>true</active>
            <codePool>community</codePool>
        </AddThis_SharingTool>
        <AddThis_PluginsGeneral>
            <active>true</active>
            <codePool>community</codePool>
        </AddThis_PluginsGeneral>
    </modules>
</config>
```

When disabling them:

```
AddThis_SmartLayers: Couldn't find declaration file
AddThis_SharingTool: Couldn't find declaration file
AddThis_PluginsGeneral: Couldn't find declaration file
```

**Comment by cmuench** [comment]
@szepeviktor Please give us more precise informations about your problem.

**Comment by szepeviktor** [comment]
I am not able to disable this module as these three modules have a common xml file.
I think Magento understand the common config.

**Comment by pocallaghan** [comment]
I believe this refers to the way the `dev:module:disable` command is implemented. It looks for a file `app/etc/modules/Vendor_Module.xml` and then updates the active node. Whilst this works in 95% of cases, there is no hard requirement for either a.) The filename to match the module name and b.) a sperate file for each extension.

Take `Mage_Newsletter` as an example, if you attempt to disable this it presumably fails. The definition for the extension is actually in `Mage_All.xml`. Some third party "extensions" which actually consist of multiple modules also contain a single module declaration file that enables all modules, in the same manner as `Mage_All.xml`.

The best solution is probably to parse all files in the `app/etc/modules` directory as xml and use xpath to see if it contains the module in question. If there are no objections to this approach I can take a crack at it.

**Comment by cmuench** [comment]
@szepeviktor @pocallaghan Yes, I understand the problem. It is not so simple as it looks like. The module:disable command should only modify the last occurance of the xml node.
Anyway... it is possible to solve this issue. At the moment I am busy with other tasks. So this issue is not on my personal priority list.
Feel free to submit a PR for this.

**Comment by pocallaghan** [comment]
@cmuench can you explain what you mean by `should only modify the last occurrence`? As far as I can tell looking at https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Developer/Module/Disableenable/AbstractCommand.php#L102, it doesn't attempt to deal with multiple occurrences of any node.

The only situation I can think of that you could be referring to is whereby an additional file is added, say `X_Disable.xml`, which is later in the load order and thus used to enable/disable the original extension without modifying the original file (I've never done it, but it seems possible theoretically). If this is what you're referring to, then that's cool, but since the current code doesn't seem to do that, I just want to ensure we're on the same page.

**Comment by pocallaghan** [comment]
I've attempted this in pull request 969. Let me know if there are any issues.

**Comment by pocallaghan** [comment]
Incidentally, how do I run that check locally and get the same results as Travis? Looking at `build/travis/script.sh` I assumed I could run `vendor/bin/php-cs-fixer --diff --dry-run -v fix`, but I got very different results. It picked up a lot more "issues".

**Comment by ktomk** [comment]
@pocallaghan: `vendor/bin/php-cs-fixer --diff --dry-run -v fix` looks good to me. it should give the same output, it's the exact same command as it is run on Travis. It depends on the working directory and must be executed in the root of the project. It should not give more errors when applied to the same files (see `.php_cs` file). Perhaps a different working directory or there are additional files in the project tree not yet committed? Or a different CS-fixer version? The lockfile should prevent that... .

**Comment by pocallaghan** [comment]
Yer, I was originally going to ask how to check it, but figured in the end if Travis is doing it, it must be in the code somewhere. So I grabbed that line out of the travis script. I'm 90% sure I was in the right directory and I'm using a new MBP with a fresh clone of the repo, so I'm not sure how the version could be wrong. I wasn't sure if Travis was somehow only running against the files touched in the commit, but couldn't see anything that would explain that.

I'll check version etc this evening, and show you the output, assuming I can replicate.

**Comment by ktomk** [comment]
Travis runs against all the files, independent to the change in the PR. But thanks for your feedback, it shows this is a bit cumbersome to use, perhaps integrating it as a composer script can do it.

**Comment by cmuench** [comment]
We have a pre-commit-config yaml to generate git commit hooks.
I use this to prevent wrong styles.

https://dev98.de/2017/01/23/a-framework-to-prevent-invalid-stuff-in-your-git-repository/

**Comment by ktomk** [comment]
Something along the lines like

     $ composer ci

springs to mind. Git hooks tend to create more problems than they solve. I've tried some of the different utils there are (another one with Composer integration is [Captain Hook](https://github.com/sebastianfeldmann/captainhook)) but most often these hooks don't check for rebase and the actual staged fragments. Can't say for [pre-commit](http://pre-commit.com) though, maybe it's more stable.

**Comment by pocallaghan** [comment]
Double checking it now, if I run ` vendor/bin/php-cs-fixer --diff --dry-run -v fix` it does as you expect. Since it takes awhile, I figured I could speed it up with `vendor/bin/php-cs-fixer --diff --dry-run -v fix src/N98/Magento/Command/Developer/Module/Disableenable/`, turns out that somehow gives a different result. Perhaps because `.php_cs` isn't in that directory so it uses the default.

**Comment by cmuench** [comment]
The pre-commit-config hook checks only the changed PHP files. So it is fast. Give it a try.

**Comment by pocallaghan** [comment]
Will give it a go, thanks.
