### ISSUE TITLE
non standard var/cache location

### ISSUE THREAD

**Issue by bw1984** [netz98/n98-magerun#964]
We are using a non-standard path for the location of the var folder, and as a result it appears that the cache: functions aren't working correctly since they are looking in the default location.

Moving the /var folder is supported out of the box in magento, despite being woefully undocumented, so I dont think a lot of people are aware of it. We have encountered lots of modules which just assume {baseURL}/var rather than obeying the explicitly set location.

It would be nice if n98-magerun checked the actual location of the var folder rather than assuming it is in the default location

our change to index.php is as follows;

```php
$parentDir = dirname(dirname(__FILE__));

$customDirectories = array(
	'media_dir' => $parentDir . DS . 'common' . DS . 'media',
	'var_dir' => $parentDir . DS . 'common' . DS . 'var'
);

Mage::run($mageRunCode, $mageRunType, $customDirectories); 
```

**Comment by pocallaghan** [comment]
Whilst this may be a feature of core Magento, it seems that in order to activate that feature you've modified the core `index.php`, since `n98-magerun` is a separate standalone application, it doesn't interact with your `index.php` file and thus it'd have no way of knowing you've modified it.

In order for `n98-magerun` to deal with this it would need to know about it somehow. Looking at [`_initMagento1`](https://github.com/netz98/n98-magerun/blob/7133c673944b3f0fa4ed1e04e1829c9a1ad5ad94/src/N98/Magento/Application.php#L779) it appears it may be possible to pass such information to `n98-magerun`. I'm not particularly familiar with these sections of the code, but I believe that's n98 config rather than Magento config, so my best bet would be that you'd need to add `app/etc/n98-magerun.yaml` with config something along the lines of:

```
init:
  options:
    media_dir: "a path"
    var_dir: "a path"
```

The biggest issues I see with that is the fact that you're dynamically generating the path. Assuming it's different in different environments, it may make more sense to add it to one of the other config locations (see [config wiki](https://github.com/netz98/n98-magerun/wiki/Config) and not have it part of your main repo. Depends on your situation.

**Comment by cmuench** [comment]
Sorry for the late response. I think @pocallaghan is writing all the facts.
We already support the third parameter of the Magento app initialization. 
You can specify the options by creating a shop specific n98-magerun.yaml file.
We do not use index.php, because n98-magerun is a CLI tool and index.php is for the web frontend.
The posted configuration in the previous comment looks good for me.
It should be possible to use the %root% placeholder in the yaml config to build a more dynamic path.
